name: docs.tandem
proxy:
  appserver:
    - port: 80/tcp
      default: true
    - port: 443/tcp
      default: true
      secure: true
services:
  appserver:
    webroot: _book
    type: nginx
    ssl: true
