name: tandemdocs
recipe: mean
config:
  node: '6.10'
  command: ./node_modules/.bin/gitbook --port 80 serve
tooling:
  gitbook:
    service: appserver_cli
    cmd:
      - ./node_modules/.bin/gitbook
