name: tandem
#excludes:
#  - node_modules
proxy:
  gitbook:
    - tandem.lndo.site
services:
  gitbook:
    type: node:10
    command: yarn gitbook serve --port 80
    build:
      - yarn
      - yarn gitbook install
tooling:
  node:
    service: gitbook
  yarn:
    service: gitbook
  gitbook:
    service: gitbook
    cmd: yarn gitbook
  mdl:
    service: gitbook
    cmd: yarn markdownlint
    description: Run markdownlinter
  test:
    service: gitbook
    cmd: yarn test
    description: Run tests
