name: tandem
excludes:
  - node_modules
proxy:
  docs:
    - docs-tandem.lndo.site:8080
services:
  docs:
    type: node:10
    build:
      - yarn install
    command: "su - node -c 'cd /app && yarn dev'"
    port: 8080
tooling:
  node:
    service: docs
  yarn:
    service: docs
  mdl:
    service: docs
    cmd: markdownlint
  vuepress:
    service: docs
  lint:
    service: docs
    cmd: yarn run lint
    description: Lint the things
  test:
    service: docs
    cmd: yarn run test
    description: Run tests
