# Docs
https://docs.{default}/:
  type: upstream
  upstream: docs:http
  cache:
    headers: ['Accept', 'Accept-Language', 'Origin']
    default_ttl: 2600
    enabled: true
  ssi:
    enabled: false
https://handbook.thinktandem.io/:
  type: redirect
  to: https://docs.{default}/

# Site
https://{default}/:
  type: upstream
  upstream: site:http
  cache:
    headers: ['Accept', 'Accept-Language', 'Origin']
    default_ttl: 2600
    enabled: true
  ssi:
    enabled: false

https://www.{default}/:
  type: redirect
  to: https://{default}/
