# Docs
https://{default}/:
  type: upstream
  upstream: docs:http
  cache:
    headers: ['Accept', 'Accept-Language', 'Origin']
    default_ttl: 2600
    enabled: true
  ssi:
    enabled: false
https://docs.v2.thinktandem.io/:
  type: redirect
  to: https://{default}/
https://handbook.thinktandem.io/:
  type: redirect
  to: https://{default}/

# New Beta Site
http://beta.thinktandem.io/:
  type: upstream
  upstream: site:http
  cache:
    headers: ['Accept', 'Accept-Language', 'Origin']
    default_ttl: 2600
    enabled: true
  ssi:
    enabled: false
