# Docs
https://docs.{default}/:
  type: upstream
  upstream: docs:http
  cache:
    headers: ["Accept", "Accept-Language", "Origin"]
    default_ttl: 2600
    enabled: true
  ssi:
    enabled: false
https://handbook.thinktandem.io/:
  type: redirect
  to: https://docs.{default}/

# Website
https://{default}/:
  type: upstream
  upstream: site:http
  cache:
    headers: ["Accept", "Accept-Language", "Origin"]
    default_ttl: 2600
    enabled: true
  ssi:
    enabled: false

  # Redirects from old v2.thinktandem.io
  redirects:
    expires: 1d
    paths: !include "redirects.yaml"

https://www.{default}/:
  type: redirect
  to: https://{default}/
