# Docs
https://docs.{default}/:
  type: upstream
  upstream: docs:http
  cache:
    headers: ["Accept", "Accept-Language", "Origin"]
    default_ttl: 2600
    enabled: true
  ssi:
    enabled: false
https://handbook.thinktandem.io/:
  type: redirect
  to: https://docs.{default}/

# Site
https://{default}/:
  type: upstream
  upstream: site:http
  cache:
    headers: ["Accept", "Accept-Language", "Origin"]
    default_ttl: 2600
    enabled: true
  ssi:
    enabled: false
  redirects:
    expires: 1d
    paths:
      "/drupal-feed.xml":
        to: "https://thinktandem.io/feed-tags-drupal.xml"
      "/services":
        to: "https://thinktandem.io/about"
      "^/services/*":
        to: "https://thinktandem.io/$1"
        regexp: true
      "^/blog/*/":
        to: "https://thinktandem.io/tag/$1"
        regexp: true
      "^/work/*/":
        to: "https://thinktandem.io/$1"
        regexp: true
https://www.{default}/:
  type: redirect
  to: https://{default}/

